spring:
  profiles:
    active: dev

  redis:
    port: 6379
    host: 127.0.0.1

  security:
    user:
      name: esanghaesee
      password: 1234


    oauth2:
      client:
        registration:
        #google 로그인 요청 URL : http://localhost:8080/oauth2/authorize/google
          # https://backend.bellytime.kr
          #"{baseUrl}/oauth2/callback/{registrationId}"
          google:
            client-id: 71318484453-sn62ah5b0rdiktov48jesea0us3vauph.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "https://backend.bellytime.kr/oauth2/callback/google"
            scope:
              - email
              - profile
        #naver 로그인 요청 URL :http://localhost:8080/oauth2/authorize/naver
          naver:
            client-id: i0Bq1fjOgdemE25lhHRz
            client-secret: GAgPjs9I_T
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"#"http://localhost:8080/login/oauth/naver"
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            client-name: naver
        #kakao 로그인 요청 URL : http://localhost:8080/oauth2/authorize/kakao
          kakao:
            client-id: 1c68643c1f9b83fba4d40c00d8d01689
            client-name: Kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}" #http://localhost:8080/login/oauth/kakao
            scope:
              - profile_nickname
              - account_email

        #provider 등록
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize # 유저의 카카오 로그인을 요청하는 곳
            token_uri: https://kauth.kakao.com/oauth/token # 엑세스 토큰을 요청하는 곳
            user-info-uri: https://kapi.kakao.com/v2/user/me # 엑세스 토큰 바탕으로 유저정보를 요청하는 곳
            user_name_attribute: id



  # 엘라스틱 서치 설정
#  elasticsearch:
#    username: root
#    password: Malangcute121!


  #  #flyway setting
  flyway:
    sql-migration-suffixes: .sql
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0


  # bean name 충돌
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  # jackson serialization off
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS : false
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

  elasticsearch:
    username: elastic
    password: Malangcute121!

#  jpa:
#    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
#    database: mysql
#

#  kafka:
#
#    consumer:
#      max-poll-records: 1
#      auto-offset-reset: earliest
##      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
##      properties: org.springframework.kafka.support.serializer.JsonDeserializer
#


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org:
      hibernate.SQL: debug
      # 엘리스틱 서치 로깅 레벨
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: TRACE



# aws 설정
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIAUN4P5GCX5AF6AS5E
      secret-key: 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




  # jpa setting
  #  jpa:
  #    hibernate:
  #      ddl-auto: create-drop
  # 네이밍 언더바 변경 없이 사용
#  jpa:
#    hibernate:
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl