spring:
  profiles:
    active: dev

  # h2 db setting
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  # mysql db setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bellytime?autoReconnect=true
    username: root
    password: 123456



  # jpa setting
  jpa:
    hibernate:
      ddl-auto: create


#  #flyway setting
  flyway:
    sql-migration-suffixes: .sql
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0

logging.level:
  org.hibernate.SQL: debug

sec:
  auth:
    secretkey: malangcute!
    validtime: 86400

